from __future__ import annotations


def render_remote_dev_demo() -> str:
    return r'''<!doctype html>
<html lang="es">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="color-scheme" content="light" />
  <title>RalfIA · Remote Developer Control Plane</title>
  <style>
    :root{--ink:#182522;--muted:#6a756f;--paper:#f3efe5;--card:#fffdf7;--line:rgba(24,37,34,.14);--orange:#ed6a3a;--teal:#147367;--teal2:#0b4e47;--green:#24a77b;--gold:#efbe4d;--danger:#a64037;--shadow:0 22px 62px rgba(54,45,31,.16)}
    *{box-sizing:border-box} body{margin:0;min-height:100vh;color:var(--ink);font-family:"Trebuchet MS","Gill Sans",sans-serif;background:radial-gradient(circle at 10% 0,rgba(239,190,77,.28),transparent 28%),radial-gradient(circle at 95% 5%,rgba(20,115,103,.18),transparent 31%),linear-gradient(90deg,rgba(24,37,34,.025) 1px,transparent 1px) 0 0/32px 32px,linear-gradient(rgba(24,37,34,.025) 1px,transparent 1px) 0 0/32px 32px,var(--paper)}
    button,textarea,select,input{font:inherit}.page{max-width:1480px;margin:auto;padding:18px}.top{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:12px 16px;margin-bottom:16px;border:1px solid var(--line);border-radius:20px;background:rgba(255,253,247,.84);backdrop-filter:blur(12px)}
    .brand{display:flex;gap:12px;align-items:center}.mark{width:44px;height:44px;border-radius:14px;display:grid;place-items:center;color:white;font-weight:900;background:linear-gradient(145deg,var(--orange),#b84022);box-shadow:0 9px 24px rgba(184,64,34,.25)}h1{margin:0;font:700 23px/1.05 Georgia,serif;letter-spacing:-.02em}.brand p{margin:4px 0 0;color:var(--muted);font-size:12px}.badges{display:flex;flex-wrap:wrap;justify-content:flex-end;gap:7px}.badge{padding:7px 10px;border:1px solid var(--line);border-radius:999px;background:white;color:var(--muted);font-size:11px;font-weight:800}.badge.live{color:#0a5743;background:#dff3e9;border-color:#9fd5bf}
    .hero{display:grid;grid-template-columns:minmax(340px,.78fr) minmax(560px,1.45fr);gap:18px;align-items:stretch}.phone-wrap,.trace{border:1px solid var(--line);border-radius:27px;background:rgba(255,253,247,.9);box-shadow:var(--shadow)}.phone-wrap{padding:18px;display:grid;place-items:center}.phone{width:min(100%,430px);height:735px;border:9px solid #1c2724;border-radius:40px;overflow:hidden;background:#efeae2;box-shadow:0 24px 50px rgba(20,30,27,.28);display:grid;grid-template-rows:auto 1fr auto;position:relative}.notch{position:absolute;z-index:3;top:0;left:50%;transform:translateX(-50%);width:130px;height:25px;border-radius:0 0 18px 18px;background:#1c2724}.chat-head{padding:30px 14px 12px;display:flex;align-items:center;gap:10px;color:white;background:linear-gradient(140deg,var(--teal),var(--teal2))}.avatar{width:40px;height:40px;border-radius:50%;display:grid;place-items:center;background:var(--orange);font-weight:900}.chat-head strong{display:block}.chat-head small{opacity:.8}.messages{padding:16px 12px;overflow:auto;background:linear-gradient(rgba(239,234,226,.9),rgba(239,234,226,.9)),radial-gradient(#b7aaa0 1px,transparent 1px) 0 0/19px 19px}.bubble{max-width:86%;padding:10px 11px;margin:7px 0;border-radius:12px;white-space:pre-wrap;font-size:13px;line-height:1.42;box-shadow:0 2px 5px rgba(0,0,0,.07)}.bubble.user{margin-left:auto;background:#d8f6ca;border-bottom-right-radius:3px}.bubble.bot{background:white;border-bottom-left-radius:3px}.bubble.system{max-width:94%;margin:8px auto;color:#6d685e;background:#fff7cf;text-align:center;font-size:11px}.bubble small{display:block;margin-top:5px;color:#777;font-size:9px;text-align:right}
    .composer{padding:10px;background:#f7f3ec;border-top:1px solid #ddd3c6}.scenario{display:grid;grid-template-columns:1fr auto;gap:7px;margin-bottom:7px}.scenario select,.scenario label{min-width:0;border:1px solid var(--line);border-radius:10px;background:white;padding:8px;font-size:11px}.scenario label{cursor:pointer;color:var(--teal);font-weight:800}.scenario input{display:none}.compose{display:grid;grid-template-columns:auto 1fr auto;gap:7px;align-items:end}.round,.send{border:0;cursor:pointer}.round{width:42px;height:42px;border-radius:50%;color:var(--teal);background:#d9eee9;font-size:18px}.round.recording{color:white;background:var(--danger);animation:pulse 1s infinite}.send{height:42px;padding:0 14px;border-radius:13px;color:white;background:var(--orange);font-weight:900}.send:disabled,.approve:disabled{opacity:.45;cursor:not-allowed}textarea{width:100%;height:44px;max-height:90px;resize:none;border:1px solid var(--line);border-radius:14px;padding:11px;background:white;outline:0}.file-note{min-height:14px;margin:5px 4px 0;color:var(--muted);font-size:9px}
    .trace{display:grid;grid-template-rows:auto auto 1fr;overflow:hidden;min-height:770px}.trace-head{padding:23px 24px 17px;border-bottom:1px solid var(--line)}.trace-head h2{margin:0;font:700 clamp(26px,3vw,39px)/1.02 Georgia,serif;letter-spacing:-.035em}.trace-head p{margin:9px 0 0;max-width:780px;color:var(--muted);line-height:1.5;font-size:13px}.facts{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;padding:12px 16px;border-bottom:1px solid var(--line);background:#eee7d9}.fact{padding:11px;border:1px solid var(--line);border-radius:14px;background:white}.fact span{display:block;color:var(--muted);font-size:9px;text-transform:uppercase;letter-spacing:.08em}.fact strong{display:block;margin-top:4px;font-size:12px;overflow:hidden;text-overflow:ellipsis}.stream{overflow:auto;padding:17px}.empty{padding:38px 20px;color:var(--muted);text-align:center}.event{display:grid;grid-template-columns:38px 1fr auto;gap:11px;position:relative;padding:0 0 18px}.event:not(:last-child):after{content:"";position:absolute;left:18px;top:38px;bottom:2px;width:2px;background:#ded7c9}.dot{z-index:1;width:38px;height:38px;border-radius:13px;display:grid;place-items:center;color:white;background:var(--teal);font-weight:900}.event.awaiting_approval .dot{background:var(--gold);color:#473712}.event.failed .dot{background:var(--danger)}.event h3{margin:1px 0 4px;font-size:13px}.event p{margin:0;color:var(--muted);font-size:11px;line-height:1.45}.meta{margin-top:7px;display:flex;gap:6px;flex-wrap:wrap}.chip{padding:4px 6px;border-radius:7px;background:#edf2ef;color:#40534d;font:700 9px/1.2 monospace}.latency{color:var(--muted);font-size:10px;white-space:nowrap}.approval{margin:0 17px 17px;padding:14px;border:1px solid rgba(237,106,58,.35);border-radius:17px;background:#fff4ec}.approval h3{margin:0 0 5px;font:700 17px Georgia,serif}.approval p{margin:0 0 10px;color:var(--muted);font-size:11px}.approve{border:0;border-radius:12px;padding:10px 14px;color:white;background:var(--teal);font-weight:900;cursor:pointer}.hidden{display:none!important}.error{color:var(--danger)}@keyframes pulse{50%{transform:scale(1.08)}}
    @media(max-width:980px){.hero{grid-template-columns:1fr}.phone{height:680px}.trace{min-height:660px}.facts{grid-template-columns:repeat(2,1fr)}}@media(max-width:520px){.page{padding:7px}.top{border-radius:14px}.badges{display:none}.phone-wrap{padding:7px}.phone{border-width:5px;border-radius:28px;height:calc(100vh - 100px)}.trace{min-height:650px}.facts{grid-template-columns:1fr 1fr}}
  </style>
</head>
<body>
<main class="page">
  <header class="top">
    <div class="brand"><div class="mark">R</div><div><h1>RalfIA Remote Developer Control Plane</h1><p>Transporte WhatsApp simulado · coordinación y ejecución verificables</p></div></div>
    <div class="badges"><span class="badge live" id="modeBadge">iniciando</span><span class="badge">sin PII</span><span class="badge">sin shell arbitraria</span><span class="badge">checkpoint humano</span></div>
  </header>
  <section class="hero">
    <div class="phone-wrap">
      <div class="phone">
        <div class="notch"></div>
        <div class="chat-head"><div class="avatar">R</div><div><strong>RalfIA</strong><small id="presence">creando sesión segura…</small></div></div>
        <div class="messages" id="messages"><div class="bubble bot">Hola. Este chat es una identidad DEMO aislada. Elige una misión, escribe o adjunta audio/imagen. Nada se ejecutará sin tu confirmación.<small>RalphiIA</small></div></div>
        <div class="composer">
          <div class="scenario"><select id="scenario"><option value="fix_quote_total">Corregir total y probar</option><option value="inspect_services">Diagnosticar fixture de servicios</option></select><label>Imagen<input id="file" type="file" accept="image/png,image/jpeg,image/webp" /></label></div>
          <div class="compose"><button class="round" id="record" title="Grabar audio">●</button><textarea id="message" placeholder="codex: corrige el total y ejecuta pruebas"></textarea><button class="send" id="send" disabled>Enviar</button></div>
          <div class="file-note" id="fileNote">Audio e imagen se procesan localmente y se marcan como no confiables.</div>
        </div>
      </div>
    </div>
    <div class="trace">
      <div class="trace-head"><h2>Lo que ocurre después de enviar</h2><p>No hay animaciones inventadas: cada fila aparece únicamente cuando el backend produce un evento real. Los IDs, tiempos, herramientas, scopes, pruebas y commit proceden de la ejecución.</p></div>
      <div class="facts"><div class="fact"><span>Sesión</span><strong id="sessionFact">—</strong></div><div class="fact"><span>Actor</span><strong id="actorFact">—</strong></div><div class="fact"><span>Task MCP</span><strong id="taskFact">—</strong></div><div class="fact"><span>Resultado</span><strong id="resultFact">esperando</strong></div></div>
      <div class="stream" id="stream"><div class="empty">Envía el primer mensaje para ver la trazabilidad completa.</div></div>
      <div class="approval hidden" id="approval"><h3>Checkpoint humano requerido</h3><p>El agente ya tiene una tarea y permisos mínimos, pero todavía no puede editar ni ejecutar pruebas.</p><button class="approve" id="approve">Confirmar ejecución segura</button></div>
    </div>
  </section>
</main>
<script>
const state={sessionId:null,token:null,action:null,checkpoint:null,media:null,recorder:null,chunks:[]};
const $=id=>document.getElementById(id);
function bubble(text,type='bot'){const el=document.createElement('div');el.className=`bubble ${type}`;el.textContent=text;const small=document.createElement('small');small.textContent=new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});el.appendChild(small);$('messages').appendChild(el);$('messages').scrollTop=$('messages').scrollHeight}
function title(value){return String(value||'').replaceAll('_',' ')}
function render(snapshot){const events=snapshot?.events||[];$('stream').replaceChildren();if(!events.length){$('stream').innerHTML='<div class="empty">Sin eventos.</div>';return}events.forEach((item,index)=>{const row=document.createElement('div');row.className=`event ${item.status||''}`;const dot=document.createElement('div');dot.className='dot';dot.textContent=String(index+1).padStart(2,'0');const content=document.createElement('div');const h=document.createElement('h3');h.textContent=title(item.event_type);const p=document.createElement('p');p.textContent=item.detail||`${item.actor} · ${item.tool||'backend'}`;content.append(h,p);const meta=document.createElement('div');meta.className='meta';[['actor',item.actor],['tool',item.tool],...Object.entries(item.evidence||{})].forEach(([k,v])=>{if(v===null||v===undefined||v==='')return;const chip=document.createElement('span');chip.className='chip';chip.textContent=`${k}: ${v}`;meta.appendChild(chip)});content.appendChild(meta);const latency=document.createElement('div');latency.className='latency';latency.textContent=item.latency_ms==null?'':`${item.latency_ms} ms`;row.append(dot,content,latency);$('stream').appendChild(row)});$('stream').scrollTop=$('stream').scrollHeight}
async function start(){const response=await fetch('/api/remote-dev/sessions',{method:'POST'});const data=await response.json();state.sessionId=data.session_id;state.token=data.session_token;$('sessionFact').textContent=data.session_id;$('actorFact').textContent=data.actor_id;$('modeBadge').textContent=data.coordination_mode;$('presence').textContent='sesión demo verificada';$('send').disabled=false}
async function send(){if(!state.sessionId)return;const text=$('message').value.trim()||'codex: ejecuta la misión seleccionada';bubble(text,'user');$('send').disabled=true;const form=new FormData();form.set('request_id',crypto.randomUUID());form.set('scenario_id',$('scenario').value);form.set('message',text);if(state.media)form.set('media',state.media,state.media.name||'recording.webm');try{const response=await fetch(`/api/remote-dev/sessions/${state.sessionId}/messages`,{method:'POST',headers:{'X-Demo-Session-Token':state.token},body:form});const data=await response.json();if(!response.ok)throw new Error(data.detail||'No se pudo crear la tarea');state.action=data.action;state.checkpoint=data.action.checkpoint;$('taskFact').textContent=data.action.task_id;$('resultFact').textContent='esperando aprobación';render(data.snapshot);bubble(`Tarea ${data.action.task_id} preparada para ${data.action.agent}. Necesito tu confirmación antes de ejecutar.`);$('approval').classList.remove('hidden');$('message').value='';state.media=null;$('file').value='';$('fileNote').textContent='Audio e imagen se procesan localmente y se marcan como no confiables.'}catch(error){bubble(`Error seguro: ${error.message}`,'system')}finally{$('send').disabled=false}}
async function approve(){if(!state.action)return;$('approve').disabled=true;bubble(`confirmar codex ${state.action.action_id}`,'user');try{const response=await fetch(`/api/remote-dev/sessions/${state.sessionId}/actions/${state.action.action_id}/approve`,{method:'POST',headers:{'Content-Type':'application/json','X-Demo-Session-Token':state.token},body:JSON.stringify({checkpoint:state.checkpoint})});const data=await response.json();if(!response.ok&&response.status!==409)throw new Error(data.detail||'Ejecución no completada');render(data.snapshot);$('resultFact').textContent=data.action.status;$('approval').classList.add('hidden');const result=data.action.status==='completed'?`Codex terminó ${data.action.job_id}. Pruebas: ${data.action.tests}. Commit: ${data.action.commit}.`:`La ejecución terminó con estado ${data.action.status}.`;bubble(result,data.action.status==='completed'?'bot':'system')}catch(error){bubble(`Error seguro: ${error.message}`,'system')}finally{$('approve').disabled=false}}
async function toggleRecord(){if(state.recorder&&state.recorder.state==='recording'){state.recorder.stop();return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});state.chunks=[];state.recorder=new MediaRecorder(stream);state.recorder.ondataavailable=e=>state.chunks.push(e.data);state.recorder.onstop=()=>{state.media=new File(state.chunks,'recording.webm',{type:state.recorder.mimeType||'audio/webm'});stream.getTracks().forEach(track=>track.stop());$('record').classList.remove('recording');$('fileNote').textContent=`Audio listo: ${Math.ceil(state.media.size/1024)} KB`};state.recorder.start();$('record').classList.add('recording');$('fileNote').textContent='Grabando… pulsa nuevamente para detener.'}catch(error){bubble('El navegador no permitió usar el micrófono. Puedes continuar con texto o imagen.','system')}}
$('send').addEventListener('click',send);$('approve').addEventListener('click',approve);$('record').addEventListener('click',toggleRecord);$('file').addEventListener('change',event=>{state.media=event.target.files[0]||null;$('fileNote').textContent=state.media?`Imagen lista: ${state.media.name}`:'Sin archivo seleccionado'});$('message').addEventListener('keydown',event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();send()}});start().catch(error=>{$('presence').textContent='sesión no disponible';bubble(`No se pudo iniciar: ${error.message}`,'system')});
</script>
</body>
</html>'''

