from __future__ import annotations


def render_remote_dev_demo() -> str:
    return r"""<!doctype html>
<html lang="es">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="color-scheme" content="light" />
  <title>RalfIA · FounderOS WhatsApp</title>
  <style>
    :root{--ink:#182522;--muted:#6a756f;--paper:#f3efe5;--card:#fffdf7;--line:rgba(24,37,34,.14);--orange:#ed6a3a;--teal:#147367;--teal2:#0b4e47;--green:#24a77b;--gold:#efbe4d;--danger:#a64037;--shadow:0 22px 62px rgba(54,45,31,.16)}
    *{box-sizing:border-box} body{margin:0;min-height:100vh;color:var(--ink);font-family:"Trebuchet MS","Gill Sans",sans-serif;background:radial-gradient(circle at 10% 0,rgba(239,190,77,.28),transparent 28%),radial-gradient(circle at 95% 5%,rgba(20,115,103,.18),transparent 31%),linear-gradient(90deg,rgba(24,37,34,.025) 1px,transparent 1px) 0 0/32px 32px,linear-gradient(rgba(24,37,34,.025) 1px,transparent 1px) 0 0/32px 32px,var(--paper)}
    button,textarea,select,input{font:inherit}.page{max-width:1480px;margin:auto;padding:18px}.top{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:12px 16px;margin-bottom:16px;border:1px solid var(--line);border-radius:20px;background:rgba(255,253,247,.84);backdrop-filter:blur(12px)}
    .brand{display:flex;gap:12px;align-items:center}.mark{width:44px;height:44px;border-radius:14px;display:grid;place-items:center;color:white;font-weight:900;background:linear-gradient(145deg,var(--orange),#b84022);box-shadow:0 9px 24px rgba(184,64,34,.25)}h1{margin:0;font:700 23px/1.05 Georgia,serif;letter-spacing:-.02em}.brand p{margin:4px 0 0;color:var(--muted);font-size:12px}.badges{display:flex;flex-wrap:wrap;justify-content:flex-end;gap:7px}.badge{padding:7px 10px;border:1px solid var(--line);border-radius:999px;background:white;color:var(--muted);font-size:11px;font-weight:800;cursor:default}.badge.lang{cursor:pointer}.badge.active{color:white;background:var(--teal);border-color:var(--teal)}.badge.live{color:#0a5743;background:#dff3e9;border-color:#9fd5bf}
    .hero{display:grid;grid-template-columns:minmax(340px,.78fr) minmax(560px,1.45fr);gap:18px;align-items:stretch}.phone-wrap,.trace{border:1px solid var(--line);border-radius:27px;background:rgba(255,253,247,.9);box-shadow:var(--shadow)}.phone-wrap{padding:18px;display:grid;place-items:center}.phone{width:min(100%,430px);height:735px;border:9px solid #1c2724;border-radius:40px;overflow:hidden;background:#efeae2;box-shadow:0 24px 50px rgba(20,30,27,.28);display:grid;grid-template-rows:auto 1fr auto;position:relative}.notch{position:absolute;z-index:3;top:0;left:50%;transform:translateX(-50%);width:130px;height:25px;border-radius:0 0 18px 18px;background:#1c2724}.chat-head{padding:30px 14px 12px;display:flex;align-items:center;gap:10px;color:white;background:linear-gradient(140deg,var(--teal),var(--teal2))}.avatar{width:40px;height:40px;border-radius:50%;display:grid;place-items:center;background:var(--orange);font-weight:900}.chat-head strong{display:block}.chat-head small{opacity:.8}.messages{padding:16px 12px;overflow:auto;background:linear-gradient(rgba(239,234,226,.9),rgba(239,234,226,.9)),radial-gradient(#b7aaa0 1px,transparent 1px) 0 0/19px 19px}.bubble{max-width:86%;padding:10px 11px;margin:7px 0;border-radius:12px;white-space:pre-wrap;font-size:13px;line-height:1.42;box-shadow:0 2px 5px rgba(0,0,0,.07)}.bubble.user{margin-left:auto;background:#d8f6ca;border-bottom-right-radius:3px}.bubble.bot{background:white;border-bottom-left-radius:3px}.bubble.system{max-width:94%;margin:8px auto;color:#6d685e;background:#fff7cf;text-align:center;font-size:11px}.bubble small{display:block;margin-top:5px;color:#777;font-size:9px;text-align:right}
    .composer{padding:10px;background:#f7f3ec;border-top:1px solid #ddd3c6}.scenario{display:grid;grid-template-columns:1fr auto;gap:7px;margin-bottom:7px}.scenario select,.scenario label,.scenario input{min-width:0;border:1px solid var(--line);border-radius:10px;background:white;padding:8px;font-size:11px}.scenario label{cursor:pointer;color:var(--teal);font-weight:800}.scenario input[type=file]{display:none}.compose{display:grid;grid-template-columns:auto 1fr auto;gap:7px;align-items:end}.round,.send{border:0;cursor:pointer}.round{width:42px;height:42px;border-radius:50%;color:var(--teal);background:#d9eee9;font-size:18px}.round.recording{color:white;background:var(--danger);animation:pulse 1s infinite}.send{height:42px;padding:0 14px;border-radius:13px;color:white;background:var(--orange);font-weight:900}.send:disabled,.approve:disabled{opacity:.45;cursor:not-allowed}textarea{width:100%;height:44px;max-height:90px;resize:none;border:1px solid var(--line);border-radius:14px;padding:11px;background:white;outline:0}.file-note{min-height:14px;margin:5px 4px 0;color:var(--muted);font-size:9px}.memory-buttons{grid-template-columns:1fr 1fr}.memory-buttons .approve{background:#ffffff;color:var(--teal);border:1px solid var(--line)}
    .trace{display:grid;grid-template-rows:auto auto 1fr;overflow:hidden;min-height:770px}.trace-head{padding:23px 24px 17px;border-bottom:1px solid var(--line)}.trace-head h2{margin:0;font:700 clamp(26px,3vw,39px)/1.02 Georgia,serif;letter-spacing:-.035em}.trace-head p{margin:9px 0 0;max-width:780px;color:var(--muted);line-height:1.5;font-size:13px}.facts{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;padding:12px 16px;border-bottom:1px solid var(--line);background:#eee7d9}.fact{padding:11px;border:1px solid var(--line);border-radius:14px;background:white}.fact span{display:block;color:var(--muted);font-size:9px;text-transform:uppercase;letter-spacing:.08em}.fact strong{display:block;margin-top:4px;font-size:12px;overflow:hidden;text-overflow:ellipsis}.stream{overflow:auto;padding:17px}.empty{padding:38px 20px;color:var(--muted);text-align:center}.event{display:grid;grid-template-columns:38px 1fr auto;gap:11px;position:relative;padding:0 0 18px}.event:not(:last-child):after{content:"";position:absolute;left:18px;top:38px;bottom:2px;width:2px;background:#ded7c9}.dot{z-index:1;width:38px;height:38px;border-radius:13px;display:grid;place-items:center;color:white;background:var(--teal);font-weight:900}.event.awaiting_approval .dot{background:var(--gold);color:#473712}.event.failed .dot{background:var(--danger)}.event h3{margin:1px 0 4px;font-size:13px}.event p{margin:0;color:var(--muted);font-size:11px;line-height:1.45}.meta{margin-top:7px;display:flex;gap:6px;flex-wrap:wrap}.chip{padding:4px 6px;border-radius:7px;background:#edf2ef;color:#40534d;font:700 9px/1.2 monospace}.latency{color:var(--muted);font-size:10px;white-space:nowrap}.approval{margin:0 17px 17px;padding:14px;border:1px solid rgba(237,106,58,.35);border-radius:17px;background:#fff4ec}.approval h3{margin:0 0 5px;font:700 17px Georgia,serif}.approval p{margin:0 0 10px;color:var(--muted);font-size:11px}.approve{border:0;border-radius:12px;padding:10px 14px;color:white;background:var(--teal);font-weight:900;cursor:pointer}.hidden{display:none!important}.error{color:var(--danger)}@keyframes pulse{50%{transform:scale(1.08)}}
    @media(max-width:980px){.hero{grid-template-columns:1fr}.phone{height:680px}.trace{min-height:660px}.facts{grid-template-columns:repeat(2,1fr)}}@media(max-width:520px){.page{padding:7px}.top{border-radius:14px}.badges{display:flex}.phone-wrap{padding:7px}.phone{border-width:5px;border-radius:28px;height:calc(100vh - 100px)}.trace{min-height:650px}.facts{grid-template-columns:1fr 1fr}}
  </style>
</head>
<body>
<main class="page">
  <header class="top">
    <div class="brand"><div class="mark">R</div><div><h1 id="appTitle">RalfIA FounderOS por WhatsApp</h1><p id="subtitle">Chat real + acciones seguras + memoria diaria privada</p></div></div>
    <div class="badges"><button class="badge lang active" id="langEs">ES</button><button class="badge lang" id="langEn">EN</button><span class="badge live" id="modeBadge">iniciando</span><span class="badge" id="modelBadge">modelo pendiente</span><span class="badge" id="privacyBadge">privado protegido</span><span class="badge" id="checkpointBadge">confirmación humana</span></div>
  </header>
  <section class="hero">
    <div class="phone-wrap">
      <div class="phone">
        <div class="notch"></div>
        <div class="chat-head"><div class="avatar">R</div><div><strong>RalfIA</strong><small id="presence">creando sesión segura…</small></div></div>
        <div class="messages" id="messages"><div class="bubble bot" id="welcome">Hola Rafael. Puedes conversar normal: cuéntame tu día, pide estado de servidores, guarda memoria o manda una tarea a Codex cuando haga falta.<small>RalfIA</small></div></div>
        <div class="composer">
          <div class="scenario"><input id="ownerCode" placeholder="código modo Rafael" /><button class="approve" id="unlock">Desbloquear memoria</button></div>
          <div class="scenario"><select id="scenario"><option value="daily_memory_checkin" data-es="Chat diario / memoria" data-en="Daily chat / memory">Chat diario / memoria</option><option value="server_4_status" data-es="Acción: estado servidor .4" data-en="Action: server .4 status">Acción: estado servidor .4</option><option value="server_5_status" data-es="Acción: estado servidor .5" data-en="Action: server .5 status">Acción: estado servidor .5</option><option value="devpost_snapshot" data-es="Acción: contexto Devpost" data-en="Action: Devpost context">Acción: contexto Devpost</option><option value="email_triage" data-es="Acción: revisar correos" data-en="Action: email triage">Acción: revisar correos</option><option value="fix_quote_total" data-es="Acción Codex: corregir total" data-en="Codex action: fix total">Acción Codex: corregir total</option><option value="inspect_services" data-es="Acción Codex: diagnosticar servicios" data-en="Codex action: inspect services">Acción Codex: diagnosticar servicios</option></select><label id="imageLabel">Imagen<input id="file" type="file" accept="image/png,image/jpeg,image/webp" /></label></div>
          <div class="compose"><button class="round" id="record" title="Grabar audio">●</button><textarea id="message" placeholder="Escribe o habla como en WhatsApp…"></textarea><button class="send" id="send" disabled>Enviar</button></div>
          <div class="scenario memory-buttons"><button class="approve" id="saveMemory">Guardar en memoria</button><button class="approve" id="searchMemory">Buscar memoria</button></div>
          <div class="file-note" id="fileNote">Audio e imagen se procesan localmente; solo se agrega el texto resultante.</div>
        </div>
      </div>
    </div>
    <div class="trace">
      <div class="trace-head"><h2 id="traceTitle">Registro real de la sesión</h2><p id="traceBody">Aquí aparece lo que realmente pasó en el backend: chat recibido, intención detectada, memoria guardada, tarea MCP creada, checkpoint humano, pruebas y resultado. Si solo conversas, no se crea una tarea falsa.</p></div>
      <div class="facts"><div class="fact"><span id="sessionLabel">Sesión</span><strong id="sessionFact">—</strong></div><div class="fact"><span id="actorLabel">Actor</span><strong id="actorFact">—</strong></div><div class="fact"><span id="taskLabel">Tarea/acción</span><strong id="taskFact">sin acción</strong></div><div class="fact"><span id="resultLabel">Resultado</span><strong id="resultFact">conversando</strong></div></div>
      <div class="stream" id="stream"><div class="empty" id="emptyState">Envía el primer mensaje para ver el registro.</div></div>
      <div class="approval hidden" id="approval"><h3 id="approvalTitle">Confirmación humana requerida</h3><p id="approvalBody">La acción ya está preparada, pero no se ejecuta hasta que tú confirmes desde esta misma sesión.</p><button class="approve" id="approve">Confirmar ejecución segura</button></div>
    </div>
  </section>
</main>
<script>
const i18n={
 es:{appTitle:'RalfIA FounderOS por WhatsApp',subtitle:'Chat real + acciones seguras + memoria diaria privada',welcome:'Hola Rafael. Puedes conversar normal: cuéntame tu día, pide estado de servidores, guarda memoria o manda una tarea a Codex cuando haga falta.',placeholder:'Escribe o habla como en WhatsApp…',send:'Enviar',unlock:'Desbloquear memoria',save:'Guardar en memoria',search:'Buscar memoria',image:'Imagen',media:'Audio e imagen se procesan localmente; solo se agrega el texto resultante.',unlocked:'Modo Rafael desbloqueado. Ahora puedes guardar o buscar Daily Life Memory real.',needUnlock:'Para guardar o buscar memoria real primero desbloquea modo Rafael.',saved:'Listo, guardé esto en Daily Life Memory. Luego lo puedes consultar desde WhatsApp.',searchResult:'Encontré esto en memoria',recording:'Grabando… pulsa nuevamente para detener.',audioReady:'Audio transcrito. Puedes editarlo antes de enviar.',imageReady:'Imagen analizada. Puedes editar el texto antes de enviarlo.',presenceReady:'listo para conversar',traceTitle:'Registro real de la sesión',traceBody:'Aquí aparece lo que realmente pasó en el backend: chat recibido, intención detectada, memoria guardada, tarea MCP creada, checkpoint humano, pruebas y resultado. Si solo conversas, no se crea una tarea falsa.',session:'Sesión',actor:'Actor',task:'Tarea/acción',result:'Resultado',noAction:'sin acción',chatting:'conversando',empty:'Envía el primer mensaje para ver el registro.',privacy:'privado protegido',checkpoint:'confirmación humana',approvalTitle:'Confirmación humana requerida',approvalBody:'La acción ya está preparada, pero no se ejecuta hasta que tú confirmes desde esta misma sesión.',approve:'Confirmar ejecución segura',modelPending:'modelo pendiente',starting:'iniciando'},
 en:{appTitle:'RalfIA FounderOS via WhatsApp',subtitle:'Real chat + safe actions + private daily memory',welcome:'Hi Rafael. You can chat normally: tell me about your day, ask for server status, save memory, or send Codex work when needed.',placeholder:'Type or speak like WhatsApp…',send:'Send',unlock:'Unlock memory',save:'Save memory',search:'Search memory',image:'Image',media:'Audio and images are processed locally; only the resulting text is added.',unlocked:'Rafael mode unlocked. You can now save or search real Daily Life Memory.',needUnlock:'Unlock Rafael mode before saving or searching real memory.',saved:'Done — I saved this to Daily Life Memory. You can query it later from WhatsApp.',searchResult:'I found this in memory',recording:'Recording… tap again to stop.',audioReady:'Audio transcribed. You can edit it before sending.',imageReady:'Image analyzed. You can edit the text before sending.',presenceReady:'ready to chat',traceTitle:'Real session log',traceBody:'This shows what really happened in the backend: chat received, intent detected, memory saved, MCP task created, human checkpoint, tests, and result. If you only chat, no fake task is created.',session:'Session',actor:'Actor',task:'Task/action',result:'Result',noAction:'no action',chatting:'chatting',empty:'Send the first message to see the log.',privacy:'private protected',checkpoint:'human checkpoint',approvalTitle:'Human confirmation required',approvalBody:'The action is prepared, but it will not run until you confirm from this same session.',approve:'Confirm safe execution',modelPending:'model pending',starting:'starting'}
};
const eventTitles={es:{session_created:'sesión creada',chat_message_received:'mensaje de chat recibido',message_received:'mensaje recibido',identity_verified:'identidad verificada',intent_classified:'intención detectada',media_processed:'medio procesado',ops_task_created:'tarea MCP creada',human_checkpoint_required:'confirmación requerida',owner_mode_unlocked:'modo Rafael desbloqueado',daily_memory_saved:'memoria guardada',human_checkpoint_approved:'confirmación aprobada',agent_started:'agente iniciado',agent_completed:'agente completado',agent_failed:'agente falló',response_ready:'respuesta lista'},en:{session_created:'session created',chat_message_received:'chat message received',message_received:'message received',identity_verified:'identity verified',intent_classified:'intent detected',media_processed:'media processed',ops_task_created:'MCP task created',human_checkpoint_required:'confirmation required',owner_mode_unlocked:'Rafael mode unlocked',daily_memory_saved:'memory saved',human_checkpoint_approved:'confirmation approved',agent_started:'agent started',agent_completed:'agent completed',agent_failed:'agent failed',response_ready:'response ready'}};
const state={sessionId:null,token:null,action:null,checkpoint:null,media:null,recorder:null,chunks:[],lang:'es',ownerVerified:false};
const $=id=>document.getElementById(id);
function t(key){return (i18n[state.lang]||i18n.es)[key]||key}
function set(id,value){const el=$(id);if(el)el.textContent=value}
function applyLang(){document.documentElement.lang=state.lang;set('appTitle',t('appTitle'));set('subtitle',t('subtitle'));$('welcome').firstChild.textContent=t('welcome');$('message').placeholder=t('placeholder');set('send',t('send'));set('unlock',t('unlock'));set('saveMemory',t('save'));set('searchMemory',t('search'));$('imageLabel').firstChild.textContent=t('image');set('fileNote',t('media'));set('traceTitle',t('traceTitle'));set('traceBody',t('traceBody'));set('sessionLabel',t('session'));set('actorLabel',t('actor'));set('taskLabel',t('task'));set('resultLabel',t('result'));set('approvalTitle',t('approvalTitle'));set('approvalBody',t('approvalBody'));set('approve',t('approve'));set('privacyBadge',t('privacy'));set('checkpointBadge',t('checkpoint'));if(!$('taskFact').dataset.hasAction){set('taskFact',t('noAction'))}if(!$('resultFact').dataset.hasResult){set('resultFact',t('chatting'))}document.querySelectorAll('#scenario option').forEach(o=>{o.textContent=o.dataset[state.lang]||o.textContent});$('langEs').classList.toggle('active',state.lang==='es');$('langEn').classList.toggle('active',state.lang==='en');if(state.sessionId)set('presence',t('presenceReady'));render(window.lastSnapshot||null)}
function bubble(text,type='bot'){const el=document.createElement('div');el.className=`bubble ${type}`;el.textContent=text;const small=document.createElement('small');small.textContent=new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});el.appendChild(small);$('messages').appendChild(el);$('messages').scrollTop=$('messages').scrollHeight}
function eventTitle(value){return (eventTitles[state.lang]||eventTitles.es)[value]||String(value||'').replaceAll('_',' ')}
function cleanValue(k,v){if(k==='provider')return state.lang==='en'?'local transcription':'transcripción local';if(k==='owner_mode')return v?'sí':'no';return v}
function render(snapshot){window.lastSnapshot=snapshot;if(!snapshot)return;const events=snapshot?.events||[];$('stream').replaceChildren();if(!events.length){$('stream').innerHTML=`<div class="empty">${t('empty')}</div>`;return}events.forEach((item,index)=>{const row=document.createElement('div');row.className=`event ${item.status||''}`;const dot=document.createElement('div');dot.className='dot';dot.textContent=String(index+1).padStart(2,'0');const content=document.createElement('div');const h=document.createElement('h3');h.textContent=eventTitle(item.event_type);const p=document.createElement('p');p.textContent=item.detail||`${item.actor} · ${item.tool||'backend'}`;content.append(h,p);const meta=document.createElement('div');meta.className='meta';[['actor',item.actor],['tool',item.tool],...Object.entries(item.evidence||{})].forEach(([k,v])=>{if(v===null||v===undefined||v==='')return;const chip=document.createElement('span');chip.className='chip';chip.textContent=`${k}: ${cleanValue(k,v)}`;meta.appendChild(chip)});content.appendChild(meta);const latency=document.createElement('div');latency.className='latency';latency.textContent=item.latency_ms==null?'':`${Math.round(item.latency_ms)} ms`;row.append(dot,content,latency);$('stream').appendChild(row)});$('stream').scrollTop=$('stream').scrollHeight}
async function start(){const response=await fetch('/api/remote-dev/sessions',{method:'POST'});const data=await response.json();state.sessionId=data.session_id;state.token=data.session_token;set('sessionFact',data.session_id);set('actorFact',data.actor_id);set('modeBadge',data.coordination_mode);set('modelBadge',data.model_requested||t('modelPending'));set('presence',t('presenceReady'));$('send').disabled=false;render({events:[]})}
function privacyFor(text){const s=(text||'').toLowerCase();if(/salud|ansiedad|mental|emocion|emoción|siento|pelea|discusi[oó]n|estr[eé]s/.test(s))return 'PRIVATE_HEALTH';if(/familia|mam[aá]|pap[aá]|hijo|hija/.test(s))return 'PRIVATE_FAMILY';if(/pareja|relaci[oó]n|elio|pelea/.test(s))return 'PRIVATE_RELATIONSHIPS';if(/dinero|deuda|pago|finanza/.test(s))return 'PRIVATE_FINANCIAL';return 'PRIVATE_PERSONAL'}
function detectActionScenario(text){const s=(text||'').toLowerCase();if(/devpost|hackathon|concurso/.test(s))return 'devpost_snapshot';if(/correo|email|mail|gmail/.test(s))return 'email_triage';if(/\.5|1\.5|servidor 5|server 5|evolution/.test(s))return 'server_5_status';if(/\.4|1\.4|servidor 4|server 4|panel/.test(s))return 'server_4_status';if(/codex|programa|corrige|commit|test|prueba|feature|bug/.test(s))return $('scenario').value==='daily_memory_checkin'?'fix_quote_total':$('scenario').value;if(/servicio|estado|reinicia|recupera|diagn[oó]stico|mantenimiento/.test(s))return $('scenario').value==='daily_memory_checkin'?'inspect_services':$('scenario').value;return null}
function wantsSave(text){return /guarda|guardar|recuerda esto|save this|remember this|save memory/.test((text||'').toLowerCase())}
function wantsSearch(text){return /busca|buscar|qué recuerdas|que recuerdas|search memory|recuerdas/.test((text||'').toLowerCase())}
async function chat(text){const response=await fetch(`/api/remote-dev/sessions/${state.sessionId}/chat`,{method:'POST',headers:{'Content-Type':'application/json','X-Demo-Session-Token':state.token},body:JSON.stringify({request_id:crypto.randomUUID(),message:text,lang:state.lang})});const data=await response.json();if(!response.ok)throw new Error(data.detail||'chat failed');render(data.snapshot);bubble(data.reply||'OK');set('taskFact',t('noAction'));delete $('taskFact').dataset.hasAction;set('resultFact',t('chatting'));delete $('resultFact').dataset.hasResult}
async function submitAction(scenarioId,text){const outbound=text|| (state.lang==='en'?'Run the selected safe action':'Ejecuta la acción segura seleccionada');const form=new FormData();form.set('request_id',crypto.randomUUID());form.set('scenario_id',scenarioId);form.set('message',outbound);if(state.media)form.set('media',state.media,state.media.name||'media');const response=await fetch(`/api/remote-dev/sessions/${state.sessionId}/messages`,{method:'POST',headers:{'X-Demo-Session-Token':state.token},body:form});const data=await response.json();if(!response.ok)throw new Error(data.detail||'No se pudo crear la acción');state.action=data.action;state.checkpoint=data.action.checkpoint;$('taskFact').dataset.hasAction='1';set('taskFact',data.action.task_id);$('resultFact').dataset.hasResult='1';set('resultFact',state.lang==='en'?'waiting for approval':'esperando aprobación');render(data.snapshot);bubble(state.lang==='en'?`Action ${data.action.task_id} is ready for ${data.action.agent}. Confirm before it runs.`:`Acción ${data.action.task_id} preparada para ${data.action.agent}. Confirma antes de ejecutar.`);$('approval').classList.remove('hidden')}
async function send(){if(!state.sessionId)return;const text=$('message').value.trim();if(!text&&!state.media)return;const outbound=text||($('fileNote').textContent||'Mensaje multimedia');bubble(outbound,'user');$('send').disabled=true;try{if(wantsSave(outbound)&&state.ownerVerified){await saveMemory(outbound,true)}else if(wantsSearch(outbound)&&state.ownerVerified){await searchMemory(outbound,true)}else{const scenario=detectActionScenario(outbound);if(scenario)await submitAction(scenario,outbound);else await chat(outbound)}$('message').value='';state.media=null;$('file').value='';set('fileNote',t('media'))}catch(error){bubble(`Error seguro: ${error.message}`,'system')}finally{$('send').disabled=false}}
async function unlockOwner(){try{const response=await fetch(`/api/remote-dev/sessions/${state.sessionId}/owner-unlock`,{method:'POST',headers:{'Content-Type':'application/json','X-Demo-Session-Token':state.token},body:JSON.stringify({code:$('ownerCode').value.trim()})});const data=await response.json();if(!response.ok)throw new Error(data.detail||'unlock failed');state.ownerVerified=true;render(data.snapshot);bubble(t('unlocked'),'system')}catch(error){bubble(`Owner mode: ${error.message}`,'system')}}
async function saveMemory(forcedText=null,alreadyBubbled=false){if(!state.ownerVerified){bubble(t('needUnlock'),'system');return}const text=(forcedText||$('message').value).trim();if(!text){bubble(state.lang==='en'?'Write something first.':'Escribe algo primero.','system');return}if(!alreadyBubbled)bubble(text,'user');const response=await fetch(`/api/remote-dev/sessions/${state.sessionId}/daily-memory`,{method:'POST',headers:{'Content-Type':'application/json','X-Demo-Session-Token':state.token},body:JSON.stringify({message:text,privacy_scope:privacyFor(text),conversation_label:'web daily check-in'})});const data=await response.json();if(!response.ok)throw new Error(data.detail||'memory save failed');render(data.snapshot);bubble(`${t('saved')}\n${data.conversation_id}`);set('resultFact',state.lang==='en'?'memory saved':'memoria guardada');$('resultFact').dataset.hasResult='1';$('message').value=''}
async function searchMemory(forcedQuery=null,alreadyBubbled=false){if(!state.ownerVerified){bubble(t('needUnlock'),'system');return}const query=(forcedQuery||$('message').value).trim();if(!query){bubble(state.lang==='en'?'Write what you want to search.':'Escribe qué quieres buscar.','system');return}if(!alreadyBubbled)bubble(query,'user');const response=await fetch(`/api/remote-dev/sessions/${state.sessionId}/daily-memory/search`,{method:'POST',headers:{'Content-Type':'application/json','X-Demo-Session-Token':state.token},body:JSON.stringify({query,limit:5})});const data=await response.json();if(!response.ok)throw new Error(data.detail||'memory search failed');const items=data.result.items||data.result.memories||data.result||[];bubble(`${t('searchResult')}:\n${JSON.stringify(items, null, 2).slice(0,900)}`);set('resultFact',state.lang==='en'?'memory searched':'memoria consultada');$('resultFact').dataset.hasResult='1'}
async function previewMedia(file){if(!file||!state.sessionId)return;const form=new FormData();form.set('media',file,file.name||'media');const response=await fetch(`/api/remote-dev/sessions/${state.sessionId}/media-preview`,{method:'POST',headers:{'X-Demo-Session-Token':state.token},body:form});const data=await response.json();if(!response.ok)throw new Error(data.detail||'media preview failed');const media=data.media||{};if(media.text){$('message').value=($('message').value.trim()?$('message').value.trim()+'\n\n':'')+media.text.trim()}set('fileNote',media.kind==='audio'?t('audioReady'):t('imageReady'))}
async function approve(){if(!state.action)return;$('approve').disabled=true;bubble(state.lang==='en'?`confirm ${state.action.action_id}`:`confirmar ${state.action.action_id}`,'user');try{const response=await fetch(`/api/remote-dev/sessions/${state.sessionId}/actions/${state.action.action_id}/approve`,{method:'POST',headers:{'Content-Type':'application/json','X-Demo-Session-Token':state.token},body:JSON.stringify({checkpoint:state.checkpoint})});const data=await response.json();if(!response.ok&&response.status!==409)throw new Error(data.detail||'Ejecución no completada');render(data.snapshot);$('resultFact').dataset.hasResult='1';set('resultFact',data.action.status);$('approval').classList.add('hidden');const result=data.action.status==='completed'?(state.lang==='en'?`Codex finished ${data.action.job_id}. Tests: ${data.action.tests}. Commit: ${data.action.commit}.`:`Codex terminó ${data.action.job_id}. Pruebas: ${data.action.tests}. Commit: ${data.action.commit}.`):(state.lang==='en'?`Execution ended with status ${data.action.status}.`:`La ejecución terminó con estado ${data.action.status}.`);bubble(result,data.action.status==='completed'?'bot':'system')}catch(error){bubble(`Error seguro: ${error.message}`,'system')}finally{$('approve').disabled=false}}
async function toggleRecord(){if(state.recorder&&state.recorder.state==='recording'){state.recorder.stop();return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});state.chunks=[];state.recorder=new MediaRecorder(stream);state.recorder.ondataavailable=e=>state.chunks.push(e.data);state.recorder.onstop=async()=>{state.media=new File(state.chunks,'recording.webm',{type:state.recorder.mimeType||'audio/webm'});stream.getTracks().forEach(track=>track.stop());$('record').classList.remove('recording');set('fileNote',state.lang==='en'?'Audio ready; transcribing…':'Audio listo; transcribiendo…');try{await previewMedia(state.media)}catch(error){bubble(`Audio: ${error.message}`,'system')}};state.recorder.start();$('record').classList.add('recording');set('fileNote',t('recording'))}catch(error){bubble(state.lang==='en'?'The browser did not allow microphone access. You can continue with text or image.':'El navegador no permitió usar el micrófono. Puedes continuar con texto o imagen.','system')}}
$('send').addEventListener('click',send);$('approve').addEventListener('click',approve);$('unlock').addEventListener('click',unlockOwner);$('saveMemory').addEventListener('click',()=>saveMemory());$('searchMemory').addEventListener('click',()=>searchMemory());$('langEs').addEventListener('click',()=>{state.lang='es';applyLang()});$('langEn').addEventListener('click',()=>{state.lang='en';applyLang()});$('record').addEventListener('click',toggleRecord);$('file').addEventListener('change',async event=>{state.media=event.target.files[0]||null;set('fileNote',state.media?(state.lang==='en'?`Image ready: ${state.media.name}`:`Imagen lista: ${state.media.name}`):(state.lang==='en'?'No file selected':'Sin archivo seleccionado'));if(state.media){try{await previewMedia(state.media)}catch(error){bubble(`Imagen: ${error.message}`,'system')}}});$('message').addEventListener('keydown',event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();send()}});applyLang();start().catch(error=>{set('presence','sesión no disponible');bubble(`No se pudo iniciar: ${error.message}`,'system')});
</script>
</body>
</html>"""
